baseurl = "/"
host = "https://de.maxgoldhouse.com"
title = "Villamartin immobilien , Playa Flamenca immobilien, Cabo Roig immobilien, Guardamar del Segura immobilien, Ciudad Quesada immobilien Costa Blanca Spain"
relativeURLs = true

[params]
  frsite = "https://fr.maxgoldhouse.com"
  ensite = "https://www.maxgoldhouse.com"
  nlsite = "https://nl.maxgoldhouse.com"
  host = "http://localhost:1313"
  phone = "+34 657 612 295"
  email = "ellen@maxgoldhouse.com"
  address = "03191 Orihuela Costa (Alicante)"
  company = "MaxGoldHouse"
  director = "Ellen Van den Broek"
  apireg: "registriertes API-Mitglied: RAICV2961"
  sold = "VERKAUFT"

[taxonomies]
  haus = "hauser"

[outputs]
    page = ["json","html"]
    section = ["json","html"] 
    immobilien = ["json","html"]
    kontakt = ["html"]
    politik = ["html"]