baseurl = "/"
host = "https://de.maxgoldhouse.com"
title = "Villamartin immobilien , Playa Flamenca immobilien, Cabo Roig immobilien, Guardamar del Segura immobilien, Ciudad Quesada immobilien Costa Blanca Spain"
relativeURLs = true

[params]
  frsite = "https://fr.maxgoldhouse.com"
  ensite = "https://www.maxgoldhouse.com"
  nlsite = "https://nl.maxgoldhouse.com"
  host = "https://mgh-3-de.web.app"
  phone = "+34 657 612 295"
  email = "ellen@maxgoldhouse.com"
  address = "03191 Pinar de Campoverde (Alicante)"
  company = "MaxGoldHouse"
  director = "Ellen Van den Broek"
  sold = "VERKAUFT"

[taxonomies]
  haus = "hauser"

[outputs]
    page = ["json","html"]
    section = ["json"] 
    immobilien = ["json","html"]
    kontakt = ["html"]
    politik = ["html"]