[[plugins]]
 package = "@netlify/plugin-local-install-core"
[[plugins]]
package = "/plugins/plugin-feed-to-content"
[plugins.inputs]
contentdirectory = "content"
partialsdirectory ="layouts/partials"
[[plugins.inputs.feeds]]
name = "immobilien"
url = "https://mgh-props.appspot.com/json/propdata/DE"
ttl = 86400

[context.production.environment]
  HUGO_VERSION = "0.80.0"

