[[plugins]]
 package = "@netlify/plugin-local-install-core"
[[plugins]]
package = "/plugins/plugin-feed-to-content"
[plugins.inputs]
contentdirectory = "content"
partialsdirectory ="layouts/partials"
[[plugins.inputs.feeds]]
name = "hauser"
url = "https://mgh-props.appspot.com/json/propdata/FR"
ttl = 86400

[context.production.environment]
  HUGO_VERSION = "0.80.0"

[[redirects]]
from = "/search/"
query = {location = "Guardamar"}
to = "/homes/guardamar-del-segura/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "guardamar"}
to = "/homes/guardamar-del-segura/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "Villamartin"}
to = "/homes/villamartin/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "villamartin"}
to = "/homes/villamartin/"
status = 301
force = false
